### ISSUE TITLE
Lost SOL after sending to Fennec Wallet

### ISSUE THREAD

**Issue by timothynest** [fox-one/fennec#11]

**Comment by lyricat** [comment]
It seems an issue with Solana by Mixin Netwotk. Please be patient and wait for the Mixin team to solve the problem. If you want to track the progress, please contact @Mixin_Network at Twitter.

**Comment by timothynest** [comment]
Still no funds 12 hours later.  Mixin hasn't responded on twitter or addressed the issue in any way. They're also deleting my messages on reddit. Any comment on why the wallet id shown in the fennec app differs from the one i get when loading the private key into an independent sol wallet? Doesn't seem very decentralized.

**Comment by lyricat** [comment]
I saw they have reply you https://twitter.com/mixin_network/status/1456460592974229506?s=21

**Comment by lyricat** [comment]
> Still no funds 12 hours later. Mixin hasn't responded on twitter or addressed the issue in any way. They're also deleting my messages on reddit. Any comment on why the wallet id shown in the fennec app differs from the one i get when loading the private key into an independent sol wallet? Doesn't seem very decentralized.

Because Mixin network is a layer 2 network, which has different architecture from solana mainnet. That’s why it doesn’t support to load existing private keys.

**Comment by lyricat** [comment]
@timothynest it's not a development issue. i will close it.
