### ISSUE TITLE
RSA session button missing in "Secret - APP SESSION"

### ISSUE THREAD

**Issue by jackjm** [fox-one/fennec#15]
The screenshot on the instruction page of "Secret - APP SESSION" shows both RSA session and Ed25519 session buttons.
https://github.com/fox-one/fennec/blob/main/docs/import_from_existing_keystore/index.md
But in my test there's only one Ed25519 session button, no RSA session button.

Chrome Version 97 on macOS Monterey v12.1, global internet access.

<img width="990" alt="Screen Shot 2022-01-23 at 10 49 18 AM" src="https://user-images.githubusercontent.com/442539/150662853-b58a3860-ad44-4232-adee-0d6df0a8bfc9.png">

Will the Ed25519 session works as well as RSA session? 
If so the instruction page should be updated.

Thx!

**Comment by lyricat** [comment]
Hi, the RSA session has been remove by Mixin Network.
Yes, you can use Ed25519 session, it's better than the RSA session.

**Comment by nicholas0310** [comment]
ok so i mabe will do this i am busy these weeks
