### ISSUE TITLE
Can no longer add contact using Mixin ID

### ISSUE THREAD

**Issue by gitalert** [fox-one/fennec#18]
Never had this problem after using constantly for 1+ year until today:
1. Click "Send"
2. Choose "Contact"
3. "Select From Contacts"
4. At this point, I have always been able to type in a Mixin ID from the messenger app and the name of that user would pop up. Now, nothing comes up. I tried multiple correct Mixin IDs on multiple different browsers too.

**Comment by lyricat** [comment]
Could you provide more information about the platform, version and browser name/version? Thanks.
