### ISSUE TITLE
Price of the asset displayed incorrectly

### ISSUE THREAD

**Issue by MonsterWong** [fox-one/fennec#2]
**Describe the bug**
During assets transferring process, the price of transferred assets is displayed incorrectly

**To Reproduce**
1. Click on 'send' button
2. chose asset e.g. "DOT"
3. Click on 'transfer to contact' button and transfer 1 DOT to contact

**Screenshots**
![image](https://user-images.githubusercontent.com/40250312/114261836-17bcbf80-99dd-11eb-87fb-2a4b07ee2064.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chorme
 - Version 0.0.3

**Comment by divisey** [comment]
fixed in lastest version.
