### ISSUE TITLE
Status Code 500 - unable to send coins from Fennec Chrome extension wallet

### ISSUE THREAD

**Issue by niclaz** [fox-one/fennec#20]
**Describe the bug**
Have been testing the Mixin network and as such used Fennec at one point in an attempt to move MOB coins off of my Signal app. After many work-arounds I got some XMR on my Fennec wallet, the balance is shown now in Fennec but I am unable to send coins from the wallet. When clicking on send (after providing a valid address) a popup appears with **'request failed with status code 500'** noted _(screenshot attached)_

TL;DR: When sending from Fennec (Chrome) a popup appears with the error status code 500

**To Reproduce**
1. Setup Fennec Chrome wallet (v 0.5.8)
2. Receive MOB / Coin 1
3. Use 4swap.org to swap coin 1 to coin 2 (XMR)
4. Attempt to send Coin 2 to a valid external address
5. Click send and popup with error code appears

**Expected behavior**
Upon clicking on Send the coins should send  ¯\_(ツ)_/¯

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 107.0.5304.88 (64 build)

**Additional context**
Please advise if possible to fix - if not what process I can follow to extract my privkey/seed for the wallet to restore elsewhere.

![Fennec WTF](https://user-images.githubusercontent.com/83479948/199813279-0b171934-5a03-4fe4-bbc8-198ceefd7aeb.PNG)

**Comment by lyricat** [comment]
According to https://Mixin.space, the withdrawal fee of XMR is  0.01 XMR. So leave 0.01 in the walllet and the withdrawal will work.

**Comment by niclaz** [comment]
Confirmed - was able to send after I manually edited the amount to leave 0.01 as a fee

This is not noted in the pop-up, and when I click on the balance in screenshot it adds the whole balance without automatically deleting the 0.01 XMR fee

Thanks for the prompt response
