### ISSUE TITLE
A QRcode to receive money from Mixin Messenger and other wallets.

### ISSUE THREAD

**Issue by lyricat** [fox-one/fennec#8]
Need a qrcode to receive money from Mixin Network based wallet.

For major assets, for example, BTC, ETH, the QRCode format could be like https://donate.cafe/cedricfung, which is supported by both Messenger and other major wallets.

For other assets, the QRCode could be formed like "mixin://transfer/{{UUID}}"

**Comment by divisey** [comment]
wait for Mixin Messenger support stable scheme
